### ISSUE TITLE
[Bug] alloy_sol_types::private::Uint<256, 4> trait impl

### ISSUE THREAD

**Issue by 0xlagrange** [alloy-rs/core#379] opened 2023-10-20 01:06 UTC
### Component

sol-types

### Operating System

Linux

### Describe the bug

<img width="1133" alt="Screenshot 2023-10-19 at 5 58 08 PM" src="https://github.com/alloy-rs/core/assets/107195066/fcb54849-fa4d-46f6-8d64-1c16c051b531">

the trait `std::borrow::Borrow<[u8; 20]>` is not implement
ed for `alloy_sol_types::private::Uint<256, 4>`

https://etherscan.io/address/0x2e4b0f20bdb1caa0886c531256efdaab925dbe72

---
<img width="1133" alt="Screenshot 2023-10-19 at 6 00 05 PM" src="https://github.com/alloy-rs/core/assets/107195066/29f22891-6ddb-415c-b27c-2e11790d77ec">

`std::borrow::Borrow<alloy_sol_types::private::U
int<256, 4>>` is not implemented for `alloy_sol_types::private::Address`

https://etherscan.io/address/0x2e4b0f20bdb1caa0886c531256efdaab925dbe72

---
<img width="1134" alt="Screenshot 2023-10-19 at 6 01 26 PM" src="https://github.com/alloy-rs/core/assets/107195066/0eec2e24-ee51-4c20-8354-268d8f904905">

the trait `std::borrow::Borrow<[u8; 32]>` is not implemented for `alloy_sol_types::private::Uint<256, 4>`

https://etherscan.io/address/0x2e4b0f20bdb1caa0886c531256efdaab925dbe72

---
<img width="1134" alt="Screenshot 2023-10-19 at 6 04 18 PM" src="https://github.com/alloy-rs/core/assets/107195066/8f638e03-6e4c-4321-b3a4-2961e6222aed">

the trait bound `u128: Borrow<alloy_sol_types::private::Uint<256, 4>>` is not satisfied

https://etherscan.io/address/0xbb37a88508d464a1bb54cf627d05e39883ae0ef9

**Comment by DaniPopes** [comment] 2023-12-01 14:26
First contract is fixed on main, second one is duplicate of #377

**Closed by DaniPopes** 2023-12-01 14:26 UTC
Labels: bug
