### ISSUE TITLE
[Bug] `sol!` macro - Error parsing enums & missing fields

### ISSUE THREAD

**Issue by 0xlagrange** [alloy-rs/core#377] opened 2023-10-20 00:45 UTC
### Component

sol! macro

### Operating System

Linux

### Describe the bug

<img width="1121" alt="Screenshot 2023-10-19 at 5 42 34 PM" src="https://github.com/alloy-rs/core/assets/107195066/a676c7c3-300e-4435-a837-aaebfa0b5133">
<img width="1108" alt="Screenshot 2023-10-19 at 5 43 16 PM" src="https://github.com/alloy-rs/core/assets/107195066/2d7bc84f-a255-489c-a55d-995257570b29">
variant defined multiple times

<img width="1126" alt="Screenshot 2023-10-19 at 5 44 47 PM" src="https://github.com/alloy-rs/core/assets/107195066/a0733dfb-86e7-47eb-9895-8921b25a6fc0">
Missing fields

https://etherscan.io/address/0xbb37a88508d464a1bb54cf627d05e39883ae0ef9

**Comment by DaniPopes** [comment] 2023-12-01 14:28
Duplicate of #376, all these different errors come from the fact that we generate two structs with the same name for `BidTooLow`, which is both an error and an event

**Closed by DaniPopes** 2023-12-01 14:28 UTC
Labels: bug
