### ISSUE TITLE
[Bug] Cannot compile alloy-json-abi at 0.8.9

### ISSUE THREAD

**Issue by palozano** [alloy-rs/core#779] opened 2024-10-22 12:03 UTC
### Component

json-abi

### What version of Alloy are you on?

0.8.9

### Operating System

macOS (Apple Silicon)

### Describe the bug

I updated to 0.8.9 and cannot compile due to errors inside alloy-json-abi.

Here's the output when building:
<img width="1033" alt="Captura de pantalla 2024-10-22 a las 14 01 48" src="https://github.com/user-attachments/assets/4179f6b6-408d-4c68-9c9e-047d70ecd709">

**Comment by DaniPopes** [comment] 2024-10-22 12:14
Duplicate of https://github.com/alloy-rs/core/issues/778. See https://github.com/alloy-rs/core/issues/778#issuecomment-2428939631.

**Closed by DaniPopes** 2024-10-22 12:14 UTC
Labels: bug
